---
- name: Install httpd
  hosts: webserver
  become: true

  tasks:
  - name: un-install httpd
    yum:
      name: httpd
      state: absent
    tags: 
     - uninstall apache

  - name: Install httpd
    yum:
      name: httpd
      state: present
    tags:
     - install apache

  - name: copy index.html
    copy: src=/home/vagrant/karuna/index.html dest=/var/www/html/index.html
    tags:
     - copy index.html

  - name: Start httpd
    service:
      name: httpd
      state: started
    tags: always
  

